version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./costco_ocr.db
      - SECRET_KEY=your-super-secret-jwt-key-change-in-production-min-32-chars
    volumes:
      - backend_data:/app/uploads
      - backend_db:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_data:
  backend_db: 